/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Scala library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala

    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    signing
    `maven-publish`

    id("com.diffplug.spotless") version "6.25.0"
}

group = "io.github.jugbot"
version = "1.0-BETA"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(libs.scala.library)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
    implementation(libs.circe.core)
    implementation(libs.circe.generic)

    // Use Scalatest for testing our library
    testImplementation(libs.junit)
    testImplementation(libs.scalatest)
    testImplementation(libs.junit.v4.v13.v2.v13)

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType<ScalaCompile>().configureEach {
    scalaCompileOptions.additionalParameters = listOf("-Xmax-inlines", "50")
}

spotless {
    scala {
        // version and configFile, scalaMajorVersion are all optional
        scalafmt("3.7.15").configFile("../.scalafmt.conf")
    }
}

val commonPom: MavenPom.() -> Unit = {
    name.set("Behavior Tree")
    description.set("Behavior tree based on rust's bonzai crate")
    url.set("https://github.com/Jugbot/scala-behavior-tree")
    licenses {
        license {
            name.set("MIT License")
            url.set("https://opensource.org/licenses/MIT")
        }
    }
    scm {
        url.set("https://github.com/Jugbot/scala-behavior-tree")
    }

    developers {
        developer {
            id.set("Jugbot")
            name.set("Lucas Pollice")
            email.set("lucas.pollice@nyu.edu")
        }
    }
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/Jugbot/scala-behavior-tree")
            credentials {
                username = project.findProperty("gpr.user") as String? ?: System.getenv("GITHUB_ACTOR")
                password = project.findProperty("gpr.key") as String? ?: System.getenv("GITHUB_TOKEN")
            }
        }
        maven {
            name = "OSSRH"
            url = uri("https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/")
            credentials {
                username = project.findProperty("ossrhUsername") as String? ?: System.getenv("MAVEN_CENTRAL_USERNAME")
                password = project.findProperty("ossrhPassword") as String? ?: System.getenv("MAVEN_CENTRAL_PASSWORD")
            }
        }
    }
    publications {
        register<MavenPublication>("default") {
            artifactId = "behavior-tree"

            from(components["java"])

            pom(commonPom)
        }
    }
}

signing {
    sign(publishing.publications["default"])
}